/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ContactForm() {
  return (
    <section className="flex relative flex-col justify-center items-end self-center px-20 py-20 mt-36 max-w-full rounded-none min-h-[288px] w-[1170px] max-md:px-5 max-md:mt-10">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/343d743644ae0d491613ac3eddcf011de33880c946d9c6a28cfd77312d8fbfbe?placeholderIfAbsent=true&apiKey=32ea7a6332e74b77babd6d1104c25fd5"
        alt=""
        className="object-cover absolute inset-0 size-full"
      />
      <div className="flex relative flex-col max-w-full w-[546px]">
        <h2 className="text-5xl font-semibold leading-none text-center text-slate-800 max-md:max-w-full max-md:text-4xl">
          Want to reach us out ?
        </h2>
        <form className="flex items-start mt-6 ml-3 max-w-full text-sm leading-6 w-[346px] max-md:ml-2.5">
          <label htmlFor="email" className="sr-only">
            Your work email address
          </label>
          <input
            type="email"
            id="email"
            className="overflow-hidden gap-2.5 self-stretch px-4 py-3.5 bg-gray-100 rounded-md text-slate-800 w-[216px]"
            placeholder="Your work email address"
            aria-label="Your work email address"
          />
          <button
            type="submit"
            className="overflow-hidden gap-2.5 self-stretch px-6 py-3.5 text-white whitespace-nowrap rounded-none bg-slate-800 max-md:px-5"
          >
            Submit
          </button>
        </form>
      </div>
    </section>
  );
}

export default ContactForm;
