/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Footer() {
  return (
    <footer className="flex relative flex-col justify-center items-center px-16 py-14 mt-36 w-full text-lg leading-none min-h-[280px] max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/7309c891f79da12d3e280d8b79b5757a5934367e06a9d11f0f5b0b394e35ecfa?placeholderIfAbsent=true&apiKey=32ea7a6332e74b77babd6d1104c25fd5"
        alt=""
        className="object-cover absolute inset-0 size-full"
      />
      <div className="flex relative flex-wrap gap-5 justify-between items-start w-full max-w-[1170px] max-md:max-w-full">
        <div className="flex flex-col self-end mt-14 max-md:mt-10 max-md:max-w-full">
          <nav className="flex flex-wrap gap-1 text-white max-md:max-w-full">
            <div className="flex flex-col">
              <div className="self-start">Download Now</div>
              <div className="flex gap-5 justify-between mt-3.5 whitespace-nowrap">
                <a href="#about">About</a>
                <a href="#features">Features</a>
              </div>
            </div>
            <div className="flex flex-col grow shrink-0 basis-0 w-fit">
              <div className="self-start">License</div>
              <div className="flex gap-6 self-end mt-3.5">
                <a href="#pricing">Pricing</a>
                <a href="#careers">Careers</a>
                <a href="#help">Help</a>
                <a href="#privacy" className="basis-auto">
                  Privacy Policy
                </a>
              </div>
            </div>
          </nav>
          <div className="self-start mt-7 text-gray-300">
            © 2020 NOKIA. All rights reserved
          </div>
        </div>
        <div className="flex flex-col self-start text-gray-300">
          <div className="self-start">Get the App</div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/b0a11e654ad198f7f033591c3f98c60f7f4a958b471304794aaefa1dfcd5d268?placeholderIfAbsent=true&apiKey=32ea7a6332e74b77babd6d1104c25fd5"
            alt="App Store"
            className="object-contain mt-5 aspect-[3.5] w-[133px]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/cbcd8b234dd4c09efdc396438c31fac52ed675a779bc224f026b5f68eaa16ac2?placeholderIfAbsent=true&apiKey=32ea7a6332e74b77babd6d1104c25fd5"
            alt="Google Play"
            className="object-contain mt-4 aspect-[3.38] w-[135px]"
          />
        </div>
      </div>
    </footer>
  );
}

export default Footer;
